export default {
  deal:{
    reportName:'deal',
    title:'电子银行支付交易统计表',
    queryData:[
      {
        choName:'机构属性:',
        name:'sx',
        show:'block',
        child:[
          {0:'全部'},
          {1:'自营'},
          {2:'代理'}
          /* {
            cname:'全部',
          },
          {
            cname:'自营',
          },
          {
            cname:'代理',
          }, */
        ]
      },
      {
        choName:'卡种类:',
        name:'kazl',
        show:'block',
        child:[
          {0:'全部'},
          {1:'自营'},
          {2:'代理'}
        ]
      },
      {
        choName:'周期类型：',
        name:'zq',
        show:'block',
        child:[
          {0:'年'},
          {1:'半年'},
          {2:'季'},
          {3:'月'},
          {4:'日'}
        ]
      },
      {
        choName:'选择半年：',
        name:'xzbn',
        show:'none',
        child:[
          {0:'上半年'},
          {1:'下半年'}
        ]
      },
      {
        choName:'选择季度：',
        name:'xzjd',
        show:'none',
        child:[
          {0:'第一季度'},
          {1:'第二季度'},
          {2:'第三季度'},
          {3:'第四季度'},
          {4:'第五季度'}
        ]
      }
    ]
  },
  claDeal:{
    reportName:'claDeal',
    title:'电子银行支付商户交易分类统计表',
    queryData:[
      {
        choName:'卡种类:',
        name:'kazl',
        show:'block',
        child:[
          {0:'全部'},
          {1:'自营'},
          {2:'代理'}
        ]
      },
      {
        choName:'周期类型：',
        name:'zq',
        show:'block',
        child:[
          {0:'年'},
          {1:'半年'},
          {2:'季'},
          {3:'月'},
          {4:'日'}
        ]
      },
      {
        choName:'选择半年：',
        name:'xzbn',
        show:'none',
        child:[
          {0:'上半年'},
          {1:'下半年'}
        ]
      },
      {
        choName:'选择季度：',
        name:'xzjd',
        show:'none',
        child:[
          {0:'第一季度'},
          {1:'第二季度'},
          {2:'第三季度'},
          {3:'第四季度'},
          {4:'第五季度'}
        ]
      }
    ]
  },
  servCharge:{
    reportName:'servCharge',
    title:'电子银行支付手续费收入统计表',
    queryData:[
      {
        choName:'机构属性:',
        name:'sx',
        show:'block',
        child:[
          {
            id:'sxall',
            cname:'全部',
            defaultChecked:'defaultChecked'
          },
          {
            id:'sxzy',
            cname:'自营',
            defaultChecked:''
          },
          {
            id:'sxdl',
            cname:'代理',
            defaultChecked:''
          },
        ]
      },
      {
        choName:'卡种类:',
        name:'kazl',
        show:'block',
        child:[
          {
            id:'kaall',
            cname:'全部',
            defaultChecked:'defaultChecked'
          },
          {
            id:'kazy',
            cname:'自营',
            defaultChecked:''
          },
          {
            id:'kadl',
            cname:'代理',
            defaultChecked:''
          },
        ]
      },
      {
        choName:'展示类型:',
        name:'zslx',
        show:'block',
        child:[
          {
            id:'shzs',
            cname:'按商户展示',
            defaultChecked:'defaultChecked'
          },
          {
            id:'jgzs',
            cname:'按机构展示',
            defaultChecked:''
          }
        ]
      },
      {
        choName:'交易渠道:',
        name:'qd',
        show:'block',
        child:[
          {
            id:'qdall',
            cname:'全部',
            defaultChecked:'defaultChecked'
          },
          {
            id:'qdzl',
            cname:'直连',
            defaultChecked:''
          },
          {
            id:'qdwl',
            cname:'网联',
            defaultChecked:''
          },
        ]
      },
      {
        choName:'周期类型：',
        name:'zq',
        show:'block',
        child:[
          {
            id:'zqn',
            cname:'年',
            defaultChecked:'defaultChecked'
          },
          {
            id:'zqbn',
            cname:'半年',
            defaultChecked:''
          },
          {
            id:'zqj',
            cname:'季',
            defaultChecked:''
          },
          {
            id:'zqy',
            cname:'月',
            defaultChecked:''
          },
          {
            id:'zqr',
            cname:'日',
            defaultChecked:''
          }
        ]
      },
      {
        choName:'统计方式:',
        name:'tj',
        show:'block',
        child:[
          {
            id:'hz',
            cname:'汇总',
          },
          {
            id:'mx',
            cname:'明细',
          }
        ]
      },
      {
        choName:'选择半年：',
        name:'xzbn',
        show:'none',
        child:[
          {
            id:'sbn',
            cname:'上半年',
          },
          {
            id:'xbn',
            cname:'下半年',
          },
        ]
      },
      {
        choName:'选择季度：',
        name:'xzjd',
        show:'none',
        child:[
          {
            id:'yjd',
            cname:'第一季度',
          },
          {
            id:'ejd',
            cname:'第二季度',
          },
          {
            id:'tjd',
            cname:'第三季度',
          },
          {
            id:'sjd',
            cname:'第四季度',
          },
        ]
      },
    ]
  },
  tiedCard:{
    reportName:'tiedCard',
    title:'电子银行支付客户量统计表',
    queryData:[
      {
        choName:'产品类型：',
        name:'cplx',
        show:'block',
        child:[
          {
            cname:'全部',
          },
          {
            cname:'微支付',
          },
          {
            cname:'快捷支付',
          },
          {
            cname:'协议支付',
          }
        ]
      },
      {
        choName:'机构属性:',
        name:'sx',
        show:'block',
        child:[
          {
            cname:'全部',
          },
          {
            cname:'自营',
          },
          {
            cname:'代理',
          },
        ]
      },
      {
        choName:'交易渠道:',
        name:'qd',
        show:'block',
        child:[
          {
            cname:'全部',
          },
          {
            cname:'直连',
          },
          {
            cname:'网联',
          },
        ]
      },
      {
        choName:'统计方式:',
        name:'tj',
        show:'block',
        child:[
          {
            cname:'汇总',
          },
          {
            cname:'明细',
          }
        ]
      },
      {
        choName:'周期类型：',
        name:'zq',
        show:'block',
        child:[
          {
            cname:'年',
          },
          {
            cname:'半年',
          },
          {
            cname:'季',
          },
          {
            cname:'月',
          },
          {
            cname:'日',
          }
        ]
      },
      {
        choName:'选择半年：',
        name:'xzbn',
        show:'none',
        child:[
          {
            cname:'上半年',
          },
          {
            cname:'下半年',
          },
        ]
      },
      {
        choName:'选择季度：',
        name:'xzjd',
        show:'none',
        child:[
          {
            cname:'第一季度',
          },
          {
            cname:'第二季度',
          },
          {
            cname:'第三季度',
          },
          {
            cname:'第四季度',
          },
        ]
      },
    ]
  }
}