export default {
    mes:[
        {
            MERCHANT_NAME:'张三',
            MERCHANT_CUST_ID:'K1',
            MERCHANT_CODE:'S1',
            PAY_AMOUNT:101,
            RETURN_AMOUNT:102,
            WITHDRAW_AMOUNT:111,
            PAY_NUM:123,
            RETURN_NUM:111,
            WITHDRAW_NUM:5432
        },
        {
            MERCHANT_NAME:'李四',
            MERCHANT_CUST_ID:'K2',
            MERCHANT_CODE:'S2',
            PAY_AMOUNT:111,
            RETURN_AMOUNT:112,
            WITHDRAW_AMOUNT:211,
            PAY_NUM:133,
            RETURN_NUM:121,
            WITHDRAW_NUM:5132
        },
        {
            MERCHANT_NAME:'王五',
            MERCHANT_CUST_ID:'K3',
            MERCHANT_CODE:'S3',
            PAY_AMOUNT:211,
            RETURN_AMOUNT:32,
            WITHDRAW_AMOUNT:221,
            PAY_NUM:53,
            RETURN_NUM:721,
            WITHDRAW_NUM:53432
        }
    ]
}