export default{
    list_name:"电子银行支付商户交易分类统计表",
    title_name:[
        {
            typ:1,
            code:"MERCHANT_NAME",
            name:"商户名称",
            cols:1,
            rows:2        
        },
        {
            typ:1,
            code:"MERCHANT_CUST_ID",
            name:"客户编码",
            cols:1,
            rows:2        
        },
        {
            typ:1,
            code:"MERCHANT_CODE",
            name:"商户编码",
            cols:1,
            rows:2        
        },
        {
            typ:1,
            code:"",
            name:"支付交易",
            cols:2,
            rows:1       
        },
        {
            typ:1,
            code:"",
            name:"退货交易",
            cols:2,
            rows:1       
        },
        {
            typ:1,
            code:"",
            name:"提现交易",
            cols:2,
            rows:1       
        },
        {
            typ:1,
            code:"",
            name:"合计",
            cols:2,
            rows:1       
        },
        {
            typ:2,
            code:"PAY_AMOUNT",
            name:"本期金额",
            cols:1,
            rows:1       
        },
        {
            typ:2,
            code:"PAY_NUM",
            name:"本期笔数",
            cols:1,
            rows:1       
        },
        {
            typ:2,
            code:"RETURN_AMOUNT",
            name:"本期金额",
            cols:1,
            rows:1       
        },
        {
            typ:2,
            code:"RETURN_NUM",
            name:"本期笔数",
            cols:1,
            rows:1       
        },
        {
            typ:2,
            code:"WITHDRAW_AMOUNT",
            name:"本期金额",
            cols:1,
            rows:1       
        },
        {
            typ:2,
            code:"WITHDRAW_NUM",
            name:"本期笔数",
            cols:1,
            rows:1       
        },
        {
            typ:2,
            code:"",
            name:"本期金额",
            cols:1,
            rows:1       
        },
        {
            typ:2,
            code:"",
            name:"本期笔数",
            cols:1,
            rows:1       
        }
    ]
}